<?php

ob_start();
?>

<?xml version="1.0" encoding="UTF-8" ?>
<!-- This is a WordPress eXtended RSS file generated by WordPress as an export of your site. -->
<!-- It contains information about your site's posts, pages, comments, categories, and other content. -->
<!-- You may use this file to transfer that content from one site to another. -->
<!-- This file is not intended to serve as a complete backup of your site. -->

<!-- To import this information into a WordPress site follow these steps: -->
<!-- 1. Log in to that site as an administrator. -->
<!-- 2. Go to Tools: Import in the WordPress admin panel. -->
<!-- 3. Install the "WordPress" importer from the list. -->
<!-- 4. Activate & Run Importer. -->
<!-- 5. Upload this file using the form provided on that page. -->
<!-- 6. You will first be asked to map the authors in this export file to users -->
<!--    on the site. For each author, you may choose to map to an -->
<!--    existing user on the site or to create a new user. -->
<!-- 7. WordPress will then import each of the posts, pages, comments, categories, etc. -->
<!--    contained in this file into your site. -->

<!-- generator="WordPress/5.5.3" created="2020-12-21 11:31" -->
<rss version="2.0"
	xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:wp="http://wordpress.org/export/1.2/"
	>

	<channel>
		<title>Entelect</title>
		<link>http://enttest.cstm.co.za</link>
		<description>Everything is possible</description>
		<pubDate>Mon, 21 Dec 2020 11:31:39 +0000</pubDate>
		<language>en-US</language>
		<wp:wxr_version>1.2</wp:wxr_version>
		<wp:base_site_url>http://enttest.cstm.co.za</wp:base_site_url>
		<wp:base_blog_url>http://enttest.cstm.co.za</wp:base_blog_url>

		<wp:author><wp:author_id>1</wp:author_id><wp:author_login><![CDATA[khabm]]></wp:author_login><wp:author_email><![CDATA[info@onecustom.co.za]]></wp:author_email><wp:author_display_name><![CDATA[khabm]]></wp:author_display_name><wp:author_first_name><![CDATA[]]></wp:author_first_name><wp:author_last_name><![CDATA[]]></wp:author_last_name></wp:author>
		<wp:author><wp:author_id>4</wp:author_id><wp:author_login><![CDATA[ivan]]></wp:author_login><wp:author_email><![CDATA[ivan@onecustom.co.za]]></wp:author_email><wp:author_display_name><![CDATA[Ivan Copeland]]></wp:author_display_name><wp:author_first_name><![CDATA[Ivan]]></wp:author_first_name><wp:author_last_name><![CDATA[Copeland]]></wp:author_last_name></wp:author>


		<generator>https://wordpress.org/?v=5.5.3</generator>

<?php
$data["header"] = ob_get_contents();
ob_end_clean();


ob_start();
?>

</channel>
</rss>

<?php
$data["footer"] = ob_get_contents();
ob_end_clean();



$file="step_1.html";
$tsv= file_get_contents($file);

$tsv= rtrim($tsv, "\n\r");
$array_0 = html_to_obj($tsv);
// echo json_encode(, JSON_PRETTY_PRINT);
$array_1 = $array_0["children"][0]["children"][0]["children"][1]["children"];
foreach ($array_1 as $key => $value) {
	$array_2[$key] = array();
	foreach ($value["children"] as $key_2 => $value_2) {
		$array_2[$key][$key_2] = "";
		if (isset($value_2["html"])) {
			$array_2[$key][$key_2] = $value_2["html"];
		}
	}
}

// $tsv= rtrim($tsv, "\n\r");
// // $array = array_map("str_getcsv", explode("\n", $tsv));
// $array = preg_split("/((\r?\n)|(\r\n?))/", $tsv);
// $array_2 = array();
// foreach ($array as $key => $value) {
//   $value = explode("\t", $value);
//   $array_2[$key] =$value;
//
// }

$array_3 = array();
foreach ($array_2 as $key => $value) {
  if ($key !== 0) {
    foreach ($value as $key_2 => $value_2) {
      $array_3[$key][$array_2[0][$key_2]] = $value_2;
      // $array_3[$key][$key_2] = $array[0];
    }
  }
}


// header('Content-Type: application/json');
// echo json_encode($array_3, JSON_PRETTY_PRINT);
// exit;


// header('Content-Type: application/json');
// echo json_encode($array_3);
// exit;

$services = array(
  "Custom Solutions",
  "Digital Transformation",
  "Strategy and Advisory",
  "Data Solutions",
  "UX",
  "Coaching & Training"
);

$industries = array(
  "Financial Services",
  "Banking",
  "Insurance",
  "Retail and Consumer Services",
  "Logistics",
  "Travel",
  "Energy",
  "Agriculture",
  "Mining and Manufacturing",
  "Industrials, Agriculture & Energy (Old)",
  "Technology",
  "Media",
  "Telecommunications",
  "Technology, Media & Telecommunications (Old)",
  "Health",
  "Education",
  "Health & Education (Old)"
);

$acf = array(
  // must be id
  // "featured_card_layout_options"=>array(
  //   "acf_code"=>"field_5f8eeed1d83f4",
  //   "import_name"=>"card_image"
  // ),
  "full_image"=>array(
    "acf_code"=>"field_5f900465eb4a0",
    "import_name"=>"Card_logo_2"
  ),
  "publication_file_downloads"=>array(
    "acf_code"=>"field_5f7720ed0848c",
    "import_name"=>""
  ),
  "company_logo"=>array(
    "acf_code"=>"field_5f7b2d3c2ccc8",
    "import_name"=>"Logo"
  ),
  "_thumbnail_id"=>array(
    "acf_code"=>"",
    "import_name"=>"Screenshots"
  ),
  "description_part_1"=>array(
    "acf_code"=>"field_5fd2211db5302",
    "import_name"=>"Content_part_1"
  ),
  "video"=>array(
    "acf_code"=>"field_5fd221a4b5304",
    "import_name"=>"Video_link"
  ),
  "description_part_2"=>array(
    "acf_code"=>"field_5fd225ec9ac99",
    "import_name"=>"Content_part_2"
  ),
  // "banner_image"=>array(
  //   "acf_code"=>"field_5fd221bab5305",
  //   "import_name"=>"banner_image"
  // ),
  "banner_color"=>array(
    "acf_code"=>"field_5fd221d5b5306",
    "import_name"=>"Banner_strip_colour"
  ),
  "quote_color"=>array(
    "acf_code"=>"field_5fd221e7b5307",
    "import_name"=>"Content_accent_colour"
  ),
  // "quote_color"=>array(
  //   "acf_code"=>"field_5fd221e7b5307",
  //   "import_name"=>"quote_color"
  // ),
  "tools"=>array(
    "acf_code"=>"field_5fd3632b01ce9",
    "import_name"=>"Sanitised list"
  ),
  // "publication_file_downloads"=>array(
  //   "acf_code"=>"field_5f7720ed0848c",
  //   "import_name"=>""
  // ),
  // "home_page_category"=>array(
  //   "acf_code"=>"field_5f8e85c800ec3",
  //   "import_name"=>""
  // ),
  // "skinny_image"=>array(
  //   "acf_code"=>"field_5f8eeed1d83be",
  //   "import_name"=>"card_image"
  // )
);

foreach ($array_3 as $key => $value) {
  ob_start();
  ?>

  <item>
    <title><?php echo $value["Heading"] ?></title>
    <content:encoded><![CDATA[<?php echo $value["Content_part_1"] ?>]]></content:encoded>
    <wp:status><![CDATA[publish]]></wp:status>
    <wp:post_type><![CDATA[projects]]></wp:post_type>

    <?php
    foreach ($services as $key_2 => $value_2) {
      if ($value[$value_2]  == "x") {

        ?>
        <category domain="services" nicename="<?php echo slugify($value_2) ?>"><![CDATA[<?php echo $value_2 ?>]]></category>
        <?php

      }

    }



    foreach ($industries as $key_2 => $value_2) {
      if ($value[$value_2]  == "x") {

        ?>
        <category domain="industries" nicename="<?php echo slugify($value_2) ?>"><![CDATA[<?php echo $value_2 ?>]]></category>
        <?php

      }
    }
    ?>


    <wp:postmeta>
      <wp:meta_key><![CDATA[dyncontel_elementor_templates]]></wp:meta_key>
      <wp:meta_value><![CDATA[12797]]></wp:meta_value>
    </wp:postmeta>
    <?php
    // <wp:postmeta>
    // <wp:meta_key><![CDATA[_thumbnail_id]]></wp:meta_key>
    // <wp:meta_value><![CDATA[<?php echo $value["Screenshots"];  // must be id questionmark>]]></wp:meta_value>
    // </wp:postmeta>

    $screenshots = array(
      "Entelect_ABSA AIMS_ENHANCING ABSA’S CORPORATE LOAN PRICING TOOLS"=>"13491",
      "Entelect_ABSA PAYMENTS_ABSA’S REVOLUTIONARY PAYMENTS SOLUTION"=>"13494",
      "Entelect_AKESO_STREAMLINING MANUAL CLINICAL PROCESSES AT AKESO"=>"13497",
      "Entelect_ALLAN GRAY_MODERNISING ALLAN GRAY DIGITAL CHANNELS FOR RETAIL"=>"13500",
      "Entelect_ALLAN GRAY_REVAMPING ALLAN GRAY’S FIND AN INDEPENDENT FINANCIAL ADVISOR PLATFORM"=>"13503",
      "Entelect_ALLAN GRAY_SUPPORTING ALLAN GRAY’S CLIENT INVESTMENT MANAGEMENT SYSTEM"=>"13506",
      "Entelect_ANGLO AMERICAN_IMPLEMENTING A SAFETY LEADING INDICATORS MANAGEMENT SYSTEM FOR ANGLO AMERICAN"=>"13509",
      "Entelect_AVIS_AVIS FLEET SERVICES’ VEHICLE COMPARISON TOOL TRANSFORMATION"=>"13512",
      "Entelect_BALOWORLD LOGISTICS_IMPROVING TECHNICAL ASSESSMENTS FOR BARLOWORLD LOGISTICS"=>"13517",
      "Entelect_BARLOWORLD EQUIPMENT_GUIDING A DIGITAL TRANSFORMATION STRATEGY FORBARLOWORLD EQUIPMENT"=>"13518",
      "Entelect_BAYPORT_INTRODUCING A TRACER MANAGEMENT SYSTEM FOR BAYPORT"=>"13521",
      "Entelect_CBI_OVERHAULING CBI ELECTRICAL’S ONLINE SCHEMATICS PLATFORM"=>"13524",
      "Entelect_CELL C_CELL C’S CUSTOMER EXPERIENCE TRANSFORMATION"=>"13527",
    );

    foreach ($acf as $key_2 => $value_2) {
      if ($key_2 == "tools") {
        $value[ $value_2["import_name"]] = serialize(explode("/",$value[ $value_2["import_name"]]));
      } elseif ($key_2 == "description_part_1") {
        $description_explode = explode("  ",$value[ $value_2["import_name"]]);


        $description_new = array();
        foreach ($description_explode as $key_3 => $value_3) {
          $description_new[] = "<p>".$value_3."</p>";
        }
        $value[ $value_2["import_name"]] = implode($description_new);
        // header('Content-Type: application/json');
        // echo "zzzz".json_encode($value[ $value_2["import_name"]], JSON_PRETTY_PRINT)."xxx";
        // exit;
      }
      if ($key_2 == "_thumbnail_id") {
        ?>

        <wp:postmeta>
  				<wp:meta_key><![CDATA[<?php echo $key_2 ?>]]></wp:meta_key>
  				<wp:meta_value><![CDATA[<?php echo $screenshots[$value[ $value_2["import_name"]]];  ?>]]></wp:meta_value>
  			</wp:postmeta>
        <?php
      } else {
        ?>
        <wp:postmeta>
          <wp:meta_key><![CDATA[<?php echo $key_2 ?>]]></wp:meta_key>
          <wp:meta_value><![CDATA[<?php echo $value[ $value_2["import_name"]] ?>]]></wp:meta_value>
        </wp:postmeta>
        <wp:postmeta>
          <wp:meta_key><![CDATA[_<?php echo $key_2 ?>]]></wp:meta_key>
          <wp:meta_value><![CDATA[<?php echo $value_2["acf_code"] ?>]]></wp:meta_value>
        </wp:postmeta>

        <?php
      }
    }
    ?>

  </item>

  <?php
  $data["body"][] = ob_get_contents();
  ob_end_clean();
}
$data["body"] = implode($data["body"]);

?>
<textarea name="name" rows="8" cols="80"><?php echo $data["header"] . $data["body"] . $data["footer"]; ?></textarea>
<textarea name="name" rows="8" cols="80"><?php echo 123; ?></textarea>
<?php



function slugify($text)
{
  // replace non letter or digits by -
  $text = preg_replace('~[^\pL\d]+~u', '-', $text);

  // transliterate
  $text = iconv('utf-8', 'us-ascii//TRANSLIT', $text);

  // remove unwanted characters
  $text = preg_replace('~[^-\w]+~', '', $text);

  // trim
  $text = trim($text, '-');

  // remove duplicate -
  $text = preg_replace('~-+~', '-', $text);

  // lowercase
  $text = strtolower($text);

  if (empty($text)) {
    return 'n-a';
  }

  return $text;
}

function html_to_obj($html) {
    $dom = new DOMDocument();
    $dom->loadHTML($html);
    return element_to_obj($dom->documentElement);
}

function element_to_obj($element) {
    $obj = array( "tag" => $element->tagName );
    foreach ($element->attributes as $attribute) {
        $obj[$attribute->name] = $attribute->value;
    }
    foreach ($element->childNodes as $subElement) {
        if ($subElement->nodeType == XML_TEXT_NODE) {
            $obj["html"] = $subElement->wholeText;
        }
        else {
            $obj["children"][] = element_to_obj($subElement);
        }
    }
    return $obj;
}
?>
